create table if not exists public.budgets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  income numeric(12,2) not null default 0 check (income >= 0),
  savings_goal numeric(12,2) not null default 0 check (savings_goal >= 0),
  updated_at timestamptz not null default now(),
  unique (user_id)
);

create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  description text not null check (char_length(description) between 1 and 120),
  category text not null,
  type text not null check (type in ('fixo', 'variavel')),
  amount numeric(12,2) not null check (amount > 0),
  occurred_on date not null default current_date,
  created_at timestamptz not null default now()
);

create index if not exists idx_expenses_user_date
on public.expenses (user_id, occurred_on desc);

alter table public.budgets enable row level security;
alter table public.expenses enable row level security;

create policy "Usuário controla o próprio orçamento"
on public.budgets for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Usuário controla os próprios gastos"
on public.expenses for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

grant select, insert, update, delete on public.budgets to authenticated;
grant select, insert, update, delete on public.expenses to authenticated;
grant usage, select on all sequences in schema public to authenticated;
